#Server port
server:
  port: 8888

#Git repo location.
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/soumenkaity/config-server-repo
  application:
    name: configserver






